language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - pypy
  - pypy3

install:
  # Install the codecov library
  - pip install codecov

script:
  # Validate code with flake8
  - python setup.py flake8

  # Run all unit tests
  - python setup.py test

after_success:
  # Send coverage statistics to codecov
  codecov

notifications:
  # Disable email notifications if something fails
  email: false
